# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b85295c48bfd05e936610f8df4654ada85acc47b50b472a2e701b3c1c3f7fdfd4e95cad4dce418fc8d541be98b8bf019baf2ab471f61e54a6912daf2b87ef6c9

test:
  secret_key_base: 3e919816638409283ecfa9bf5be61f07cb9f685e4d10b1fc76f2c128c2b52523c68778ac9a15410764356c8552fc81004f424ba0270e5f6f7b757ba43e035d8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
